# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.box = "roboxes/ubuntu2004"

  # Workaround for missing libraries on Debian-based boxes:
  # /opt/VBoxGuestAdditions-7.0.8/bin/VBoxClient: error while loading shared libraries: libXt.so.6: cannot open shared object file: No such file or directory
  # See https://github.com/dotless-de/vagrant-vbguest/issues/425#issuecomment-1515225030
  config.vbguest.installer_hooks[:before_install] = [
    "apt-get update",
    "apt-get -y install libxt6 libxmu6 bzip2 tar"
  ]
  config.vbguest.installer_hooks[:after_install] = [
    "VBoxClient --version"
  ]
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    # Explicitly guest type (above) and OS type
    vb.customize ["modifyvm", :id, "--ostype", 'Ubuntu20_LTS_64']
    # Enabling I/O APIC is required for 64-bit guests
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    # Force newer VirtualBox default graphics controller for Linux guests
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    # Explicitly disable unnecessary features for better performance
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
    vb.customize ['modifyvm', :id, '--clipboard', 'disabled']
    vb.customize ['modifyvm', :id, '--draganddrop', 'disabled']
    vb.customize ['modifyvm', :id, '--vrde', 'off']
  end

end
