# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.box = "gusztavvargadr/windows-server-2022-standard-core"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows

  config.vm.provider :virtualbox do |vb|
    vb.memory = 8192
    vb.cpus = 4
    vb.gui = false
    # Explicitly set guest version and type
    vb.customize ['modifyvm', :id, '--ostype', 'Windows2022_64']
    # Enabling I/O APIC is required for 64-bit guests
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    # Explicitly use Windows guest default graphics controller
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'vboxsvga']
    # Explicitly disable unnecessary features for better performance
    vb.customize ['modifyvm', :id, '--accelerate3d', 'off']
    vb.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
    vb.customize ['modifyvm', :id, '--clipboard', 'disabled']
    vb.customize ['modifyvm', :id, '--draganddrop', 'disabled']
    vb.customize ['modifyvm', :id, '--vrde', 'off']
  end

  config.vm.provision "shell", path: "../provision.ps1", privileged: true, args: "-AdminUser vagrant -AdminPassword vagrant -NewHostname winworker"
  config.vm.provision :reload
  config.vm.provision "shell", path: "../install-containerd-runtime.ps1", privileged: true
end
