# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.box = "mloskot/sig-windows-dev-tools-ubuntu-2204"
  config.vm.box_version = "1.0"

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 4
    vb.memory = 8192
    vb.gui = false
    # Explicitly  Windows guest version and type
    vb.customize ["modifyvm", :id, "--ostype", 'Ubuntu22_LTS_64']
    # Enabling I/O APIC is required for 64-bit guests
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    # Force newer VirtualBox default graphics controller for Linux guests
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    # Explicitly disable unnecessary features for better performance
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    vb.customize ["modifyvm", :id, "--accelerate2dvideo", "off"]
    vb.customize ['modifyvm', :id, '--clipboard', 'disabled']
    vb.customize ['modifyvm', :id, '--draganddrop', 'disabled']
    vb.customize ['modifyvm', :id, '--vrde', 'off']
  end

end
